import { CPMTable } from "./../@types/index";

export const TEST_DATA: CPMTable = [
  {
    name: "A",
    key: "mantine-qsribptk2",
    duration: 5,
    predessors: "",
    eft: 0,
    est: 0,
    lft: 0,
    lst: 0,
    slack: 0,
  },
  {
    name: "B",
    key: "mantine-pl3ljt9cu",
    duration: 8,
    predessors: "A",
    eft: 0,
    est: 0,
    lft: 0,
    lst: 0,
    slack: 0,
  },
  {
    name: "C",
    key: "mantine-42g2vt7ui",
    duration: 5,
    predessors: "B",
    eft: 0,
    est: 0,
    lft: 0,
    lst: 0,
    slack: 0,
  },
  {
    name: "D",
    key: "mantine-rq4bnxwom",
    duration: 10,
    predessors: "B",
    eft: 0,
    est: 0,
    lft: 0,
    lst: 0,
    slack: 0,
  },
  {
    name: "E",
    key: "mantine-c4t37g2tj",
    duration: 8,
    predessors: "C,D",
    eft: 0,
    est: 0,
    lft: 0,
    lst: 0,
    slack: 0,
  },
  {
    name: "F",
    key: "mantine-vkt0siz79",
    duration: 5,
    predessors: "E",
    eft: 0,
    est: 0,
    lft: 0,
    lst: 0,
    slack: 0,
  },
];
