import { randomId } from "@mantine/hooks";
import { CPMTable } from "./../@types/index";

export const TEST_DATA: CPMTable[] = [
  [
    {
      name: "A",
      key: randomId(),
      duration: 5,
      predessors: "",
      eft: 0,
      est: 0,
      lft: 0,
      lst: 0,
      slack: 0,
    },
    {
      name: "B",
      key: randomId(),
      duration: 8,
      predessors: "A",
      eft: 0,
      est: 0,
      lft: 0,
      lst: 0,
      slack: 0,
    },
    {
      name: "C",
      key: randomId(),
      duration: 5,
      predessors: "B",
      eft: 0,
      est: 0,
      lft: 0,
      lst: 0,
      slack: 0,
    },
    {
      name: "D",
      key: randomId(),
      duration: 10,
      predessors: "B",
      eft: 0,
      est: 0,
      lft: 0,
      lst: 0,
      slack: 0,
    },
    {
      name: "E",
      key: randomId(),
      duration: 8,
      predessors: "C,D",
      eft: 0,
      est: 0,
      lft: 0,
      lst: 0,
      slack: 0,
    },
    {
      name: "F",
      key: randomId(),
      duration: 5,
      predessors: "E",
      eft: 0,
      est: 0,
      lft: 0,
      lst: 0,
      slack: 0,
    },
  ],
  [
    {
      name: "A",
      key: randomId(),
      duration: 4,
      predessors: "",
      eft: 0,
      est: 0,
      lft: 0,
      lst: 0,
      slack: 0,
    },
    {
      name: "B",
      key: randomId(),
      duration: 5,
      predessors: "",
      eft: 0,
      est: 0,
      lft: 0,
      lst: 0,
      slack: 0,
    },
    {
      name: "C",
      key: randomId(),
      duration: 5,
      predessors: "A",
      eft: 0,
      est: 0,
      lft: 0,
      lst: 0,
      slack: 0,
    },
    {
      name: "D",
      key: randomId(),
      duration: 6,
      predessors: "A",
      eft: 0,
      est: 0,
      lft: 0,
      lst: 0,
      slack: 0,
    },
    {
      name: "E",
      key: randomId(),
      duration: 5,
      predessors: "B,C",
      eft: 0,
      est: 0,
      lft: 0,
      lst: 0,
      slack: 0,
    },
    {
      name: "F",
      key: randomId(),
      duration: 4,
      predessors: "D",
      eft: 0,
      est: 0,
      lft: 0,
      lst: 0,
      slack: 0,
    },
    {
      name: "G",
      key: randomId(),
      duration: 5,
      predessors: "E",
      eft: 0,
      est: 0,
      lft: 0,
      lst: 0,
      slack: 0,
    },
  ],
];
